service: serverless-backend
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  # environment:
  #   DYNAMODB_TABLE: todo-items
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

functions:
  pushNotification: # name called to invoke the function
    handler: push-notification.push # fileName.functionName
    environment:
      PUBLIC_VAPID_KEY: ${env:PUBLIC_VAPID_KEY}
      PRIVATE_VAPID_KEY: ${env:PRIVATE_VAPID_KEY}
      MALTO_EMAIL: ${env:MALTO_EMAIL}
    events:
      - http: 
          path: push
          method: get
          cors: true
      - schedule: cron(0 0 9 * ? *)
      # 9am UTM === 10pm nz

  saveSubscription:
    handler: save-subscription.save
    events:
      - http: 
          path: subscription
          method: post
          cors: true

  updateProductivity:
    handler: update-productivity.update
    events:
      - http: 
          path: productivity
          method: post
          cors: true

  getProductivityItem:
    handler: get-productivity-item.get
    events:
      - http: 
          path: productivity
          method: get
          cors: true

  putItemInTable:
    handler: put-item-in-table.put
    events:
      - http: 
          path: put
          method: post
          cors: true


# todo: add cron scedualler 
# https://docs.aws.amazon.com/systems-manager/latest/userguide/reference-cron-and-rate-expressions.html